### ISSUE TITLE
请标注原作者

### ISSUE THREAD

**Issue by antfu** [toyobayashi/mp-handle#1]
你好，我是汉兜的作者 Anthony。很高兴你喜欢汉兜并做了小程序的版本，但是看了一圈似乎没有发现在小程序与源码中对原原始版本与原作者的 Credit。还请麻烦遵照协议与开源精神，补全 Credit 信息：

- 简单声明小程序为汉兜的社区延伸版本，与原汉兜游戏并无直接关联
- 汉兜游戏或仓库的链接 https://handle.antfu.me ｜ https://github.com/antfu/handle
- 原作者 Anthony 与 Inès

希望以上信息可以至少出现在 **小程序的帮助界面** 与 **仓库的README** 中。

感谢！

**Comment by toyobayashi** [comment]
@antfu 非常抱歉，我会马上在 readme 和下一版小程序帮助页面中补全这些信息。另外请问我是否可以在小程序中投放流量主广告位呢？

**Comment by antfu** [comment]
只需要 Credit 与 Fork 说明（主要避免玩家混淆）即可，其他你都可以自行安排决定，谢谢
